/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.8 */

#ifndef PB_FRAME_PB_H_INCLUDED
#define PB_FRAME_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _Chunk {
    uint32_t lenght;
    pb_callback_t data;
} Chunk;

typedef struct _Frame {
    uint32_t chunk_max;
    uint32_t chunk_left;
    Chunk chunk;
} Frame;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define Chunk_init_default                       {0, {{NULL}, NULL}}
#define Frame_init_default                       {0, 0, Chunk_init_default}
#define Chunk_init_zero                          {0, {{NULL}, NULL}}
#define Frame_init_zero                          {0, 0, Chunk_init_zero}

/* Field tags (for use in manual encoding/decoding) */
#define Chunk_lenght_tag                         3
#define Chunk_data_tag                           4
#define Frame_chunk_max_tag                      1
#define Frame_chunk_left_tag                     2
#define Frame_chunk_tag                          3

/* Struct field encoding specification for nanopb */
#define Chunk_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, UINT32,   lenght,            3) \
X(a, CALLBACK, REQUIRED, BYTES,    data,              4)
#define Chunk_CALLBACK pb_default_field_callback
#define Chunk_DEFAULT NULL

#define Frame_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, UINT32,   chunk_max,         1) \
X(a, STATIC,   REQUIRED, UINT32,   chunk_left,        2) \
X(a, STATIC,   REQUIRED, MESSAGE,  chunk,             3)
#define Frame_CALLBACK NULL
#define Frame_DEFAULT NULL
#define Frame_chunk_MSGTYPE Chunk

extern const pb_msgdesc_t Chunk_msg;
extern const pb_msgdesc_t Frame_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define Chunk_fields &Chunk_msg
#define Frame_fields &Frame_msg

/* Maximum encoded size of messages (where known) */
/* Chunk_size depends on runtime parameters */
/* Frame_size depends on runtime parameters */

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
