/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.4 */

#ifndef PB_COMM_PB_H_INCLUDED
#define PB_COMM_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _JoystickMessage {
    int32_t ax;
    int32_t ay;
    int32_t az;
    int32_t aw;
    int32_t bA;
    int32_t bB;
    int32_t bX;
    int32_t bY;
    int32_t bL;
    int32_t bR;
    int32_t bU;
    int32_t bD;
    int32_t ck;
} JoystickMessage;

typedef struct _TelemetryMessage {
    uint32_t btl;
    float btv;
    int32_t x;
    int32_t y;
    int32_t z;
    bool e1;
    bool e2;
    bool e3;
    float t1;
    float t2;
    uint32_t ck;
} TelemetryMessage;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define JoystickMessage_init_default             {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
#define TelemetryMessage_init_default            {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
#define JoystickMessage_init_zero                {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
#define TelemetryMessage_init_zero               {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define JoystickMessage_ax_tag                   1
#define JoystickMessage_ay_tag                   2
#define JoystickMessage_az_tag                   3
#define JoystickMessage_aw_tag                   4
#define JoystickMessage_bA_tag                   5
#define JoystickMessage_bB_tag                   6
#define JoystickMessage_bX_tag                   7
#define JoystickMessage_bY_tag                   8
#define JoystickMessage_bL_tag                   9
#define JoystickMessage_bR_tag                   10
#define JoystickMessage_bU_tag                   11
#define JoystickMessage_bD_tag                   12
#define JoystickMessage_ck_tag                   13
#define TelemetryMessage_btl_tag                 1
#define TelemetryMessage_btv_tag                 2
#define TelemetryMessage_x_tag                   3
#define TelemetryMessage_y_tag                   4
#define TelemetryMessage_z_tag                   5
#define TelemetryMessage_e1_tag                  6
#define TelemetryMessage_e2_tag                  7
#define TelemetryMessage_e3_tag                  8
#define TelemetryMessage_t1_tag                  9
#define TelemetryMessage_t2_tag                  10
#define TelemetryMessage_ck_tag                  11

/* Struct field encoding specification for nanopb */
#define JoystickMessage_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, SINT32,   ax,                1) \
X(a, STATIC,   REQUIRED, SINT32,   ay,                2) \
X(a, STATIC,   REQUIRED, SINT32,   az,                3) \
X(a, STATIC,   REQUIRED, SINT32,   aw,                4) \
X(a, STATIC,   REQUIRED, INT32,    bA,                5) \
X(a, STATIC,   REQUIRED, INT32,    bB,                6) \
X(a, STATIC,   REQUIRED, INT32,    bX,                7) \
X(a, STATIC,   REQUIRED, INT32,    bY,                8) \
X(a, STATIC,   REQUIRED, INT32,    bL,                9) \
X(a, STATIC,   REQUIRED, INT32,    bR,               10) \
X(a, STATIC,   REQUIRED, INT32,    bU,               11) \
X(a, STATIC,   REQUIRED, INT32,    bD,               12) \
X(a, STATIC,   REQUIRED, INT32,    ck,               13)
#define JoystickMessage_CALLBACK NULL
#define JoystickMessage_DEFAULT NULL

#define TelemetryMessage_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, UINT32,   btl,               1) \
X(a, STATIC,   REQUIRED, FLOAT,    btv,               2) \
X(a, STATIC,   REQUIRED, SINT32,   x,                 3) \
X(a, STATIC,   REQUIRED, SINT32,   y,                 4) \
X(a, STATIC,   REQUIRED, SINT32,   z,                 5) \
X(a, STATIC,   REQUIRED, BOOL,     e1,                6) \
X(a, STATIC,   REQUIRED, BOOL,     e2,                7) \
X(a, STATIC,   REQUIRED, BOOL,     e3,                8) \
X(a, STATIC,   REQUIRED, FLOAT,    t1,                9) \
X(a, STATIC,   REQUIRED, FLOAT,    t2,               10) \
X(a, STATIC,   REQUIRED, UINT32,   ck,               11)
#define TelemetryMessage_CALLBACK NULL
#define TelemetryMessage_DEFAULT NULL

extern const pb_msgdesc_t JoystickMessage_msg;
extern const pb_msgdesc_t TelemetryMessage_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define JoystickMessage_fields &JoystickMessage_msg
#define TelemetryMessage_fields &TelemetryMessage_msg

/* Maximum encoded size of messages (where known) */
#define JoystickMessage_size                     123
#define TelemetryMessage_size                    51

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
