/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.4 */

#include "comm.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(JoystickMessage, JoystickMessage, AUTO)


PB_BIND(TelemetryMessage, TelemetryMessage, AUTO)



